name: continuous-integration
on: [push, pull_request]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment variables
        run: |
          INSTALL_PREFIX="$GITHUB_WORKSPACE/install-prefix"

      - name: Checkout mdo-utils repository
        uses: actions/checkout@v2
        with:
          path: 'mdo-utils'

      - name: Configure mdo-utils
        shell: bash
        run: |
          pushd mdo-utils # ~/mdo-utils/
          mkdir build
          pushd build # ~/mdo-utils/build/
          cmake .. -DENABLE_TESTS=ON -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX

      - name: Compile mdo-utils
        shell: bash
        run: cmake --build .

      - name: Test mdo-utils
        shell: bash
        run: cmake --test .

      - name: Install mdo-utils
        shell: bash
        run: |
          cmake --install .
          popd # ~/mdo-utils/
          popd # ~/

      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          path: 'canary'
          submodules: 'true'

      - name: Configure
        shell: bash
        run: |
          pushd canary # ~/canary/
          mkdir build
          pushd build  # ~/canary/build/
          cmake .. -DENABLE_TESTS=ON -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX

      - name: Compile
        shell: bash
        run: cmake --build .

      - name: Test
        shell: bash
        run: ctest .

      - name: Install
        shell: bash
        run: |
          cmake --install .
          popd # ~/canary/
          popd # ~/

      - name: Upload install prefix artifact
        uses: actions/upload-artifact@v2
        with:
          name: install-prefix
          path: install-prefix
